# Generated by Django 5.2.1 on 2025-08-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlcanceOperacion',
            fields=[
                ('cod_alcance', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alcance_operacion',
                'db_table_comment': 'Alcances de operación 2025 disponibles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_entidad', models.CharField(max_length=50)),
                ('id_entidad', models.IntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'auditoria',
                'ordering': ['-fecha_hora'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('cod_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categorias',
                'db_table_comment': 'Catálogo de categorías para insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClasificacionInsumo',
            fields=[
                ('cod_clasificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('ruta', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clasificacion_insumo',
                'db_table_comment': 'Clasificación y características adicionales de los insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('cod_concepto', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('evaluacion', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle_concepto', models.CharField(blank=True, max_length=10000, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('pdf', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'concepto',
                'db_table_comment': 'Conceptos asociados a los insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('cod_depto', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_depto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamentos',
                'db_table_comment': 'Catálogo de departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleInsumo',
            fields=[
                ('cod_detalle', models.IntegerField(primary_key=True, serialize=False)),
                ('escala', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('cubrimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_disposicion', models.DateField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('vigencia', models.CharField(blank=True, max_length=50, null=True)),
                ('ruta_archivo', models.TextField(blank=True, max_length=500, null=True)),
                ('porcentaje_cubrimiento', models.TextField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'detalle_insumo',
                'db_table_comment': 'Detalles específicos de los insumos, ahora incluyendo información de usuario, clasificación, zona y centro poblado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('cod_entidad', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom_entidad', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'entidades',
                'db_table_comment': 'Catálogo de entidades con códigos en formato de siglas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosInsumo',
            fields=[
                ('estado', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Estado de Insumo',
                'verbose_name_plural': 'Estados de Insumos',
                'db_table': 'estados_insumo',
                'db_table_comment': 'Catálogo de estados posibles para insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('cod_grupo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'grupo',
                'db_table_comment': 'Grupos para clasificación de municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('cod_insumo', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'insumos',
                'db_table_comment': 'Registro principal de insumos, con información de categoría pero sin usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaArchivosPre',
            fields=[
                ('id_lista_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_disposicion', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('path_file', models.CharField(blank=True, max_length=500, null=True)),
                ('hash_contenido', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario_windows', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_memoria', models.CharField(blank=True, help_text='Peso del archivo en memoria', max_length=100, null=True)),
            ],
            options={
                'db_table': 'lista_archivos_preo',
                'db_table_comment': 'Tabla que almacena la lista de archivos preoperativos relacionados con clasificaciones de insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MecanismoDetalle',
            fields=[
                ('cod_mecanismo_detalle', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'mecanismo_detalle',
                'db_table_comment': 'Detalles de los mecanismos de operación',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MecanismoGeneral',
            fields=[
                ('cod_mecanismo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'mecanismo_general',
                'db_table_comment': 'Mecanismos generales 2025 disponibles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MecanismoOperacion',
            fields=[
                ('cod_operacion', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'mecanismo_operacion',
                'db_table_comment': 'Dominio para operaciones directas en municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('cod_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_municipio', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('nom_territorial', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('mecanismo_general', models.CharField(blank=True, max_length=100, null=True)),
                ('mecanismo_detalle', models.CharField(blank=True, max_length=100, null=True)),
                ('alcance_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('mecanismo_operacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'municipios',
                'db_table_comment': 'Catálogo de municipios con su departamento correspondiente e información de operación',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PathDirPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ruta Postoperativa',
                'verbose_name_plural': 'Rutas Postoperativas',
                'db_table': 'path_dir_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PathDirPre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ruta Preoperativa',
                'verbose_name_plural': 'Rutas Preoperativas',
                'db_table': 'path_dir_pre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesionalesSeguimiento',
            fields=[
                ('cod_profesional', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_profesional', models.CharField(max_length=100)),
                ('correo_profesional', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Profesional de Seguimiento',
                'verbose_name_plural': 'Profesionales de Seguimiento',
                'db_table': 'profesionales_seguimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesionalMunicipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Asignación Profesional-Municipio',
                'verbose_name_plural': 'Asignaciones Profesionales-Municipios',
                'db_table': 'profesional_municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesionalTerritorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Asignación Profesional-Territorial',
                'verbose_name_plural': 'Asignaciones Profesionales-Territoriales',
                'db_table': 'profesional_territorial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolesSeguimiento',
            fields=[
                ('rol_profesional', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Rol de Seguimiento',
                'verbose_name_plural': 'Roles de Seguimiento',
                'db_table': 'roles_seguimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TerritorialesIgac',
            fields=[
                ('nom_territorial', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Territorial IGAC',
                'verbose_name_plural': 'Territoriales IGAC',
                'db_table': 'territoriales_igac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposFormato',
            fields=[
                ('cod_formato_tipo', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tipos_formato',
                'db_table_comment': 'Catálogo de tipos de formato/extensiones de archivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposInsumos',
            fields=[
                ('tipo_insumo', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tipos_insumos',
                'db_table_comment': 'Dominio de tipos de insumos: primarios y secundarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('cod_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'db_table_comment': 'Información de usuarios del sistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('zona', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'zonas',
                'db_table_comment': 'Catálogo de zonas disponibles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentrosPoblados',
            fields=[
                ('cod_centro_poblado', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_centro_poblado', models.CharField(blank=True, max_length=200, null=True)),
                ('area_oficial_ha', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_municipio', models.ForeignKey(db_column='cod_municipio', on_delete=django.db.models.deletion.CASCADE, to='preoperacion.municipios')),
            ],
            options={
                'verbose_name': 'Centro Poblado',
                'verbose_name_plural': 'Centros Poblados',
                'db_table': 'centros_poblados',
                'db_table_comment': 'Centros poblados por municipio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InfoAdministrativa',
            fields=[
                ('cod_info_admin', models.AutoField(primary_key=True, serialize=False)),
                ('id_gestor_catas', models.CharField(blank=True, max_length=200, null=True)),
                ('gestor_prestador_servicio', models.CharField(blank=True, max_length=200, null=True)),
                ('publicacion_year', models.CharField(blank=True, max_length=50, null=True)),
                ('vigencia_rural', models.CharField(blank=True, max_length=100, null=True)),
                ('vigencia_urbana', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_rural', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_urbano', models.CharField(blank=True, max_length=100, null=True)),
                ('predios_rurales', models.CharField(blank=True, max_length=100, null=True)),
                ('area_terreno_rural_m2', models.CharField(blank=True, max_length=100, null=True)),
                ('area_terreno_rural_ha', models.CharField(blank=True, max_length=100, null=True)),
                ('area_construida_rural_m2', models.CharField(blank=True, max_length=100, null=True)),
                ('avaluo_rural', models.CharField(blank=True, max_length=100, null=True)),
                ('predios_urbanos', models.CharField(blank=True, max_length=100, null=True)),
                ('area_terreno_urbana_m2', models.CharField(blank=True, max_length=100, null=True)),
                ('area_terreno_urbana_ha', models.CharField(blank=True, max_length=100, null=True)),
                ('area_construida_urbana_m2', models.CharField(blank=True, max_length=100, null=True)),
                ('avaluo_urbano_1', models.CharField(blank=True, max_length=100, null=True)),
                ('avaluo_urbano_2', models.CharField(blank=True, max_length=100, null=True)),
                ('total_predios', models.CharField(blank=True, max_length=100, null=True)),
                ('total_area_terreno_m2', models.CharField(blank=True, max_length=100, null=True)),
                ('total_area_terreno_ha', models.CharField(blank=True, max_length=100, null=True)),
                ('total_area_construida_m2', models.CharField(blank=True, max_length=100, null=True)),
                ('total_avaluos', models.CharField(blank=True, max_length=100, null=True)),
                ('area_geografica_rural_ha', models.CharField(blank=True, max_length=100, null=True)),
                ('area_geografica_urbana_ha', models.CharField(blank=True, max_length=100, null=True)),
                ('area_rural_estados_catastrales_ha', models.CharField(blank=True, max_length=100, null=True)),
                ('area_urbana_estados_catastrales_ha', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cod_municipio', models.ForeignKey(db_column='cod_municipio', on_delete=django.db.models.deletion.CASCADE, to='preoperacion.municipios')),
            ],
            options={
                'verbose_name': 'Información Administrativa',
                'verbose_name_plural': 'Información Administrativa',
                'db_table': 'info_administrativa',
                'db_table_comment': 'Información administrativa catastral por municipio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_entidad', models.CharField(max_length=50)),
                ('id_entidad', models.IntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('datos_contexto', models.JSONField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora del cambio')),
                ('leido', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['fecha_cambio'], name='notificacio_fecha_c_60120d_idx'), models.Index(fields=['fecha_cambio', 'tipo_entidad'], name='notificacio_fecha_c_4ec2b6_idx'), models.Index(fields=['fecha_cambio', 'leido'], name='notificacio_fecha_c_995eba_idx'), models.Index(fields=['-fecha_cambio'], name='notificacio_fecha_c_73033c_idx'), models.Index(fields=['tipo_entidad', 'leido', 'fecha_cambio'], name='notificacio_tipo_en_e50827_idx'), models.Index(fields=['leido', '-fecha_cambio'], name='notificacio_leido_b66860_idx')],
            },
        ),
    ]
