"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
import multiprocessing
try:
    multiprocessing.set_start_method('spawn', force=True)
except RuntimeError:
    pass


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar configuración adicional de email desde archivo separado
# (para cuando no se tiene acceso al .env principal)
env_email_path = BASE_DIR / '.env.email'
if env_email_path.exists():
    load_dotenv(env_email_path, override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-hom+z1ps1pao@i@#t46g^4-bu!wh=f#pxf_k9ghg-^_v28h87=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'



REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        # Token con expiración (8 horas por defecto)
        'preoperacion.auth.ExpiringTokenAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 30000,
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'preoperacion',
    'postoperacion',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'corsheaders',
    'coreapi',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # ✅ AGREGADOS: Middlewares de seguridad
    'backend.middleware_seguridad.SecurityHeaderValidationMiddleware',
    'backend.middleware_seguridad.ParameterPollutionProtectionMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # CSRF DESACTIVADO - Permite acceso desde cualquier origen
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'




TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'gestion_dato_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', '1234'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'client_encoding': os.getenv('DB_CLIENT_ENCODING', 'UTF8'),
        },
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

NETWORK_SHARES = {
    'REPOSITORY_BASE': {
        'path': os.getenv('REPOSITORY_BASE_PATH', r'\\repositorio\DirGesCat\2510SP\H_Informacion_Consulta\Sub_Proy'),
        # Si necesitas credenciales para acceder al recurso compartido, agrégalas al .env
        'username': os.getenv('REPOSITORY_USERNAME', None),
        'password': os.getenv('REPOSITORY_PASSWORD', None),
        'domain': os.getenv('REPOSITORY_DOMAIN', None)
    },
    'PDF_REPOSITORY': {
        'path': os.getenv('PDF_REPOSITORY_PATH', r'\\repositorio\DirGesCat\2510SP\H_Informacion_Consulta\Sub_Proy\05_grup_trab\11_gest_info\2025\01_insu_primr\CONCEPTOS_ORTO_CARTO'),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ✅ CORREGIDO: ALLOWED_HOSTS ahora valida que esté configurado en producción
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else ['localhost', '127.0.0.1']

# Validar que ALLOWED_HOSTS esté configurado en producción
if not DEBUG:
    if not os.getenv('ALLOWED_HOSTS'):
        import warnings
        warnings.warn("⚠️ ALLOWED_HOSTS debe estar configurado en producción")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', '180'))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME_DAYS', '1'))),
}

# ============================================================================
# ✅ CORRECCIÓN DE SEGURIDAD: CORS Configuration
# ============================================================================
import re

# ✅ CORREGIDO: NO permitir todos los orígenes en producción
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

# ✅ CORREGIDO: Usar whitelist de orígenes permitidos
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if os.getenv('CORS_ALLOWED_ORIGINS') else []

# Solo permitir credenciales con orígenes específicos
CORS_ALLOW_CREDENTIALS = True if CORS_ALLOWED_ORIGINS or CORS_ALLOW_ALL_ORIGINS else False

# Validar configuración en producción
if not DEBUG and CORS_ALLOW_ALL_ORIGINS:
    import warnings
    warnings.warn(
        "⚠️ ADVERTENCIA CRÍTICA: CORS_ALLOW_ALL_ORIGINS=True en producción. "
        "Configure CORS_ALLOWED_ORIGINS en .env"
    )

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "access-control-allow-headers"
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS'
]

CORS_EXPOSE_HEADERS = [
    "authorization",
    "content-type"
]

CORS_PREFLIGHT_MAX_AGE = 86400  # 24 horas

# ============================================================================
# ✅ AGREGADO: Configuración de seguridad adicional
# ============================================================================

# CSRF Configuration
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else []

# Security Headers
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True

# Session Security
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 3600

# ============================================================================
# ✅ CORRECCIÓN CRÍTICA: Configuración de proxy para evitar bucle de redirecciones
# ============================================================================
# Esta línea le indica a Django que confíe en el header X-Forwarded-Proto
# enviado por nginx para determinar si la conexión es segura (HTTPS).
# Sin esto, Django siempre intentará redirigir a HTTPS causando un bucle infinito.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# HTTPS en producción
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ✅ AGREGADO: Configuración para Parameter Pollution Protection
PARAMETER_POLLUTION_ACTION = os.getenv('PARAMETER_POLLUTION_ACTION', 'reject')
ALLOWED_DUPLICATE_PARAMS = ['filter', 'tag', 'category']

# ============================================================================
# TOKEN EXPIRATION CONFIGURATION
# ============================================================================
# Tiempo de vida del token en horas (default: 8 horas = 1 jornada laboral)
TOKEN_EXPIRATION_HOURS = int(os.getenv('TOKEN_EXPIRATION_HOURS', '8'))

# ============================================================================
# EMAIL CONFIGURATION (Para recuperación de contraseña)
# ============================================================================
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@gestiondato.igac.gov.co')

# URL del frontend para links en emails de recuperación
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://gestiondato.duckdns.org')