# Generated by Django 5.2.1 on 2025-08-11 15:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preoperacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionInfoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Descripción del concepto de calificación', max_length=255, verbose_name='Concepto')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor numérico de la calificación (0.0 a 1.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0, message='El valor no puede ser menor a 0'), django.core.validators.MaxValueValidator(1.0, message='El valor no puede ser mayor a 1')], verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Calificación de Información Post',
                'verbose_name_plural': 'Calificaciones de Información Post',
                'db_table': 'calificacion_info_post',
                'ordering': ['valor', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='ComponentesPost',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_componente', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Componente Post (DEPRECATED)',
                'verbose_name_plural': 'Componentes Post (DEPRECATED)',
                'db_table': 'componentes_post',
            },
        ),
        migrations.CreateModel(
            name='DisposicionPost',
            fields=[
                ('id_disposicion', models.AutoField(primary_key=True, serialize=False)),
                ('dispuesto', models.BooleanField(default=False)),
                ('fecha_disposicion', models.DateField(blank=True, null=True)),
                ('ruta_acceso', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('evaluado', models.BooleanField(default=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('cod_municipio', models.ForeignKey(db_column='cod_municipio', on_delete=django.db.models.deletion.CASCADE, related_name='disposicion_postoperacion', to='preoperacion.municipios')),
            ],
            options={
                'verbose_name': 'Disposición Post V2',
                'verbose_name_plural': 'Disposiciones Post V2',
                'db_table': 'disposicion_post',
            },
        ),
        migrations.CreateModel(
            name='ArchivosPost',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_completa', models.TextField(unique=True)),
                ('fecha_disposicion', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('hash_contenido', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario_windows', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_memoria', models.CharField(blank=True, help_text='Peso del archivo en memoria', max_length=100, null=True)),
                ('id_disposicion', models.ForeignKey(db_column='id_disposicion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='archivos_relacionados', to='postoperacion.disposicionpost')),
            ],
            options={
                'verbose_name': 'Archivo Post V2',
                'verbose_name_plural': 'Archivos Post V2',
                'db_table': 'archivos_post',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionArchivosPost',
            fields=[
                ('id_evaluacion', models.AutoField(help_text='Identificador único de la evaluación', primary_key=True, serialize=False, verbose_name='ID Evaluación')),
                ('id_archivo', models.IntegerField(db_index=True, help_text='Referencia al archivo original en archivos_post', verbose_name='ID Archivo Original')),
                ('nombre_archivo', models.CharField(help_text='Nombre del archivo evaluado', max_length=255, verbose_name='Nombre del Archivo')),
                ('ruta_completa', models.TextField(help_text='Ruta completa del archivo en el sistema', verbose_name='Ruta Completa')),
                ('fecha_disposicion', models.DateField(blank=True, help_text='Fecha cuando se dispuso el archivo', null=True, verbose_name='Fecha de Disposición')),
                ('observacion_original', models.CharField(blank=True, help_text='Observación original del archivo', max_length=500, null=True, verbose_name='Observación Original')),
                ('hash_contenido', models.CharField(blank=True, help_text='Hash para verificar integridad del archivo', max_length=255, null=True, verbose_name='Hash del Contenido')),
                ('usuario_windows', models.CharField(blank=True, help_text='Usuario Windows que creó el archivo', max_length=100, null=True, verbose_name='Usuario Windows')),
                ('peso_memoria', models.CharField(blank=True, help_text='Peso del archivo en memoria', max_length=100, null=True, verbose_name='Peso en Memoria')),
                ('evaluacion_archivo', models.IntegerField(blank=True, default=1, help_text='ID de la calificación en calificacion_info_post', null=True, verbose_name='Evaluación del Archivo')),
                ('estado_archivo', models.CharField(choices=[('PENDIENTE', 'Pendiente de Evaluación'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REQUIERE_AJUSTES', 'Requiere Ajustes')], db_index=True, default='PENDIENTE', help_text='Estado actual de la evaluación del archivo', max_length=50, verbose_name='Estado del Archivo')),
                ('observaciones_evaluacion', models.TextField(blank=True, help_text='Observaciones específicas de la evaluación realizada', null=True, verbose_name='Observaciones de Evaluación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha cuando se creó el registro de evaluación', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de la última actualización', verbose_name='Fecha de Actualización')),
                ('usuario_evaluacion', models.CharField(blank=True, help_text='Usuario que realizó o actualizó la evaluación', max_length=100, null=True, verbose_name='Usuario Evaluador')),
                ('evaluado', models.BooleanField(default=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('id_disposicion', models.ForeignKey(db_column='id_disposicion', help_text='Disposición asociada al archivo', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_archivos', to='postoperacion.disposicionpost', verbose_name='Disposición')),
            ],
            options={
                'verbose_name': 'Evaluación de Archivo Post',
                'verbose_name_plural': 'Evaluaciones de Archivos Post',
                'db_table': 'evaluacion_archivos_post',
                'ordering': ['-fecha_creacion', 'nombre_archivo'],
                'permissions': [('can_evaluate_files', 'Puede evaluar archivos'), ('can_approve_files', 'Puede aprobar archivos'), ('can_view_evaluations', 'Puede ver evaluaciones')],
            },
        ),
        migrations.CreateModel(
            name='HistorialPropietarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_archivo', models.CharField(choices=[('preoperacion', 'Pre-operación'), ('postoperacion', 'Post-operación')], help_text='Tipo de archivo: preoperación o postoperación', max_length=20)),
                ('id_archivo', models.IntegerField(help_text='ID del archivo según el tipo')),
                ('id_notificacion', models.IntegerField(blank=True, help_text='Referencia a la notificación que registró el cambio', null=True)),
                ('propietario_anterior', models.CharField(blank=True, help_text='Usuario que era propietario', max_length=100, null=True)),
                ('propietario_nuevo', models.CharField(help_text='Usuario que se convirtió en propietario', max_length=100)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, help_text='Momento en que comenzó la propiedad del nuevo propietario')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='NULL si es el propietario actual, timestamp cuando fue reemplazado', null=True)),
                ('detalles', models.JSONField(blank=True, help_text='Información adicional como ruta, nombre archivo, etc.', null=True)),
            ],
            options={
                'verbose_name': 'Historial de Propietario',
                'verbose_name_plural': 'Historial de Propietarios',
                'db_table': 'historial_propietarios',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['tipo_archivo', 'id_archivo'], name='hist_tipo_id_idx'), models.Index(fields=['propietario_nuevo'], name='hist_prop_nuevo_idx'), models.Index(fields=['propietario_anterior'], name='hist_prop_ant_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='hist_fechas_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificacionesPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_entidad', models.CharField(max_length=50)),
                ('id_entidad', models.IntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('datos_contexto', models.JSONField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora del cambio')),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notificación Post',
                'verbose_name_plural': 'Notificaciones Post',
                'db_table': 'notificaciones_post',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['fecha_cambio'], name='notif_post_fecha_idx'), models.Index(fields=['fecha_cambio', 'tipo_entidad'], name='notif_post_fecha_tipo_idx'), models.Index(fields=['fecha_cambio', 'leido'], name='notif_post_fecha_leido_idx'), models.Index(fields=['-fecha_cambio'], name='notif_post_fecha_desc_idx'), models.Index(fields=['tipo_entidad', 'leido', 'fecha_cambio'], name='noti_post_tipo_leido_fecha_idx'), models.Index(fields=['leido', '-fecha_cambio'], name='noti_post_leido_fecha_desc_idx')],
            },
        ),
        migrations.CreateModel(
            name='PathDirPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cod_municipio', models.ForeignKey(db_column='cod_municipio', on_delete=django.db.models.deletion.CASCADE, related_name='pathdirpost_postoperacion', to='preoperacion.municipios')),
            ],
            options={
                'verbose_name': 'Ruta de Directorio Post',
                'verbose_name_plural': 'Rutas de Directorios Post',
                'db_table': 'path_dir_post',
            },
        ),
        migrations.AddIndex(
            model_name='disposicionpost',
            index=models.Index(fields=['cod_municipio'], name='disp_post_municipio_idx'),
        ),
        migrations.AddIndex(
            model_name='disposicionpost',
            index=models.Index(fields=['ruta_acceso'], name='disp_post_ruta_idx'),
        ),
        migrations.AddIndex(
            model_name='disposicionpost',
            index=models.Index(fields=['fecha_disposicion'], name='disp_post_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='archivospost',
            index=models.Index(fields=['id_disposicion'], name='arch_post_disposicion_idx'),
        ),
        migrations.AddIndex(
            model_name='archivospost',
            index=models.Index(fields=['nombre_archivo'], name='arch_post_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='archivospost',
            index=models.Index(fields=['fecha_disposicion'], name='arch_post_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='archivospost',
            index=models.Index(fields=['usuario_windows'], name='arch_post_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionarchivospost',
            index=models.Index(fields=['id_disposicion'], name='eval_arch_post_disp_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionarchivospost',
            index=models.Index(fields=['id_archivo'], name='eval_arch_post_arch_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionarchivospost',
            index=models.Index(fields=['estado_archivo'], name='eval_arch_post_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionarchivospost',
            index=models.Index(fields=['evaluacion_archivo'], name='eval_arch_post_eval_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionarchivospost',
            index=models.Index(fields=['fecha_creacion'], name='eval_arch_post_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionarchivospost',
            index=models.Index(fields=['usuario_evaluacion'], name='eval_arch_post_usuario_idx'),
        ),
    ]
