# Generated by Django 5.2.9 on 2025-12-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postoperacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionarchivospost',
            name='evaluacion_archivo_anterior',
            field=models.IntegerField(blank=True, help_text='ID de la calificación anterior (para restaurar)', null=True, verbose_name='Evaluación Anterior'),
        ),
        migrations.AddField(
            model_name='evaluacionarchivospost',
            name='fecha_calificacion_masiva',
            field=models.DateTimeField(blank=True, help_text='Fecha de la última calificación masiva', null=True, verbose_name='Fecha Calificación Masiva'),
        ),
        migrations.AddField(
            model_name='evaluacionarchivospost',
            name='lote_calificacion_masiva',
            field=models.CharField(blank=True, help_text='Identificador del lote de calificación masiva (UUID)', max_length=100, null=True, verbose_name='Lote Calificación Masiva'),
        ),
    ]
