# Generated by Django 5.2.9 on 2025-12-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postoperacion', '0002_add_mass_qualification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaArchivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(help_text='Nombre del archivo al momento de la acción', max_length=255, verbose_name='Nombre del Archivo')),
                ('ruta_completa', models.TextField(help_text='Ruta completa del archivo', verbose_name='Ruta Completa')),
                ('accion', models.CharField(choices=[('UPLOAD', 'Archivo subido'), ('DOWNLOAD', 'Archivo descargado'), ('RENAME', 'Archivo renombrado'), ('DELETE', 'Archivo eliminado'), ('MOVE', 'Archivo movido'), ('COPY', 'Archivo copiado'), ('MODIFY', 'Archivo modificado')], db_index=True, help_text='Tipo de acción realizada', max_length=20, verbose_name='Acción')),
                ('usuario', models.CharField(db_index=True, help_text='Usuario que realizó la acción', max_length=150, verbose_name='Usuario')),
                ('usuario_email', models.EmailField(blank=True, help_text='Email del usuario que realizó la acción', max_length=254, null=True, verbose_name='Email del Usuario')),
                ('plataforma', models.CharField(choices=[('WEB', 'Plataforma Web'), ('WINDOWS', 'Windows/Red'), ('API', 'API Externa'), ('SCRIPT', 'Script Automático')], default='WEB', help_text='Plataforma desde donde se realizó la acción', max_length=20, verbose_name='Plataforma')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de la acción', verbose_name='Fecha de Acción')),
                ('detalles', models.JSONField(blank=True, help_text='Información adicional de la acción (nombre anterior, tamaño, etc.)', null=True, verbose_name='Detalles')),
                ('ip_cliente', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True, verbose_name='IP del Cliente')),
                ('tamano_archivo', models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True, verbose_name='Tamaño del Archivo')),
                ('id_archivo', models.ForeignKey(blank=True, db_column='id_archivo', help_text='Referencia al archivo en archivos_post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_registros', to='postoperacion.archivospost', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Auditoría de Archivo',
                'verbose_name_plural': 'Auditoría de Archivos',
                'db_table': 'auditoria_archivos',
                'ordering': ['-fecha_accion'],
                'indexes': [models.Index(fields=['id_archivo'], name='audit_arch_archivo_idx'), models.Index(fields=['accion'], name='audit_arch_accion_idx'), models.Index(fields=['usuario'], name='audit_arch_usuario_idx'), models.Index(fields=['fecha_accion'], name='audit_arch_fecha_idx'), models.Index(fields=['ruta_completa'], name='audit_arch_ruta_idx'), models.Index(fields=['-fecha_accion', 'accion'], name='audit_arch_fecha_acc_idx')],
            },
        ),
    ]
