# Generated by Django - Fix duplicate evaluacion and disposicion records

from django.db import migrations, models


def cleanup_evaluacion_duplicates(apps, schema_editor):
    """
    Remove duplicate evaluacion_archivos_post records by ruta_completa.
    Keeps the record with the most evaluation progress (evaluado=True first,
    then most recently updated).
    """
    from django.db import connection
    with connection.cursor() as cursor:
        # Count duplicates first
        cursor.execute("""
            SELECT COUNT(*) - COUNT(DISTINCT ruta_completa)
            FROM evaluacion_archivos_post
        """)
        dup_count = cursor.fetchone()[0]

        if dup_count > 0:
            # Delete duplicates, keeping the best record per ruta_completa
            cursor.execute("""
                DELETE FROM evaluacion_archivos_post
                WHERE id_evaluacion NOT IN (
                    SELECT DISTINCT ON (ruta_completa) id_evaluacion
                    FROM evaluacion_archivos_post
                    ORDER BY ruta_completa, evaluado DESC, fecha_actualizacion DESC NULLS LAST
                )
            """)
            print(f"  Cleaned up {cursor.rowcount} duplicate evaluacion records")
        else:
            print("  No duplicate evaluacion records found")


def merge_duplicate_disposiciones(apps, schema_editor):
    """
    Merge DisposicionPost records that have both Windows and Linux format paths
    for the same directory. Keeps the Linux format one (matches the indexer).
    Converts remaining Windows-only paths to Linux format.
    """
    from django.db import connection
    with connection.cursor() as cursor:
        # Find all disposiciones with Windows format paths (starting with \\)
        cursor.execute(r"""
            SELECT id_disposicion, ruta_acceso, cod_municipio
            FROM disposicion_post
            WHERE ruta_acceso LIKE '\\%'
        """)
        windows_disposiciones = cursor.fetchall()

        if not windows_disposiciones:
            print("  No Windows-format disposicion paths found")
            return

        merged_count = 0
        converted_count = 0

        for win_id, win_ruta, cod_muni in windows_disposiciones:
            if not win_ruta:
                continue

            # Convert Windows path to Linux format
            linux_ruta = win_ruta.replace('\\\\repositorio\\DirGesCat', '/mnt/repositorio')
            linux_ruta = linux_ruta.replace('\\', '/')

            # Check if a Linux format version already exists
            cursor.execute("""
                SELECT id_disposicion FROM disposicion_post
                WHERE ruta_acceso = %s
            """, (linux_ruta,))

            linux_match = cursor.fetchone()

            if linux_match:
                linux_id = linux_match[0]

                # Move archivos from Windows disposicion to Linux one
                cursor.execute("""
                    UPDATE archivos_post
                    SET id_disposicion = %s
                    WHERE id_disposicion = %s
                """, (linux_id, win_id))

                # Move evaluaciones from Windows disposicion to Linux one
                cursor.execute("""
                    UPDATE evaluacion_archivos_post
                    SET id_disposicion = %s
                    WHERE id_disposicion = %s
                """, (linux_id, win_id))

                # Delete the Windows-format disposicion
                cursor.execute("""
                    DELETE FROM disposicion_post WHERE id_disposicion = %s
                """, (win_id,))

                merged_count += 1
            else:
                # No Linux version exists, convert the Windows path to Linux format
                cursor.execute("""
                    UPDATE disposicion_post
                    SET ruta_acceso = %s
                    WHERE id_disposicion = %s
                """, (linux_ruta, win_id))
                converted_count += 1

        if merged_count > 0:
            print(f"  Merged {merged_count} duplicate disposicion records (Windows -> Linux)")
        if converted_count > 0:
            print(f"  Converted {converted_count} Windows-format paths to Linux format")


class Migration(migrations.Migration):

    dependencies = [
        ('postoperacion', '0003_add_auditoria_archivos'),
    ]

    operations = [
        # Step 1: Clean up duplicate evaluacion records
        migrations.RunPython(
            cleanup_evaluacion_duplicates,
            migrations.RunPython.noop,
        ),
        # Step 2: Merge duplicate disposicion records (Windows vs Linux paths)
        migrations.RunPython(
            merge_duplicate_disposiciones,
            migrations.RunPython.noop,
        ),
        # Step 3: Add UNIQUE constraint on evaluacion_archivos_post.ruta_completa
        # This makes the database trigger's ON CONFLICT (ruta_completa) DO NOTHING work correctly
        migrations.AlterField(
            model_name='evaluacionarchivospost',
            name='ruta_completa',
            field=models.TextField(
                unique=True,
                verbose_name='Ruta Completa',
                help_text='Ruta completa del archivo en el sistema',
            ),
        ),
    ]
