# Generated by Django 5.2.1 on 2025-08-11 15:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preoperacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoriosOperacion',
            fields=[
                ('cod_dir_operacion', models.AutoField(primary_key=True, serialize=False)),
                ('path_directorio', models.CharField(help_text='Ruta completa del directorio (hasta 600 caracteres)', max_length=600)),
                ('nombre_directorio', models.CharField(max_length=255)),
                ('nivel_profundidad', models.IntegerField(default=0, help_text='Nivel de profundidad en la jerarquía (0=raíz)', null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_propietario', models.CharField(blank=True, max_length=100, null=True)),
                ('total_archivos', models.IntegerField(default=0, null=True)),
                ('total_subdirectorios', models.IntegerField(default=0, null=True)),
                ('peso_total_bytes', models.BigIntegerField(default=0, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('cod_municipio', models.ForeignKey(db_column='cod_municipio', help_text='Código del municipio (FK a municipios)', on_delete=django.db.models.deletion.CASCADE, to='preoperacion.municipios')),
                ('directorio_padre', models.ForeignKey(blank=True, db_column='directorio_padre', help_text='Referencia al directorio padre para crear jerarquía', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.directoriosoperacion')),
            ],
            options={
                'verbose_name': 'Directorio de Operación',
                'verbose_name_plural': 'Directorios de Operación',
                'db_table': 'directorios_operacion',
                'ordering': ['cod_municipio', 'nivel_profundidad', 'nombre_directorio'],
            },
        ),
        migrations.CreateModel(
            name='ArchivosOperacion',
            fields=[
                ('id_archivo_operacion', models.AutoField(primary_key=True, serialize=False)),
                ('path_file', models.CharField(help_text='Ruta completa del archivo (hasta 600 caracteres)', max_length=600)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_disposicion', models.DateTimeField(blank=True, null=True)),
                ('usuario_windows', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_memoria', models.BigIntegerField(default=0, help_text='Peso del archivo en bytes', null=True)),
                ('tipo_archivo', models.CharField(blank=True, help_text='Tipo: archivo normal o directorio especial (.gdb, .eslpk, etc.)', max_length=50, null=True)),
                ('hash_archivo', models.CharField(blank=True, max_length=64, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('cod_dir_operacion', models.ForeignKey(db_column='cod_dir_operacion', help_text='Referencia al directorio de operación', on_delete=django.db.models.deletion.CASCADE, to='app.directoriosoperacion')),
            ],
            options={
                'verbose_name': 'Archivo de Operación',
                'verbose_name_plural': 'Archivos de Operación',
                'db_table': 'archivos_operacion',
                'ordering': ['-fecha_registro', 'nombre_archivo'],
            },
        ),
        migrations.CreateModel(
            name='DirectoriosTransv',
            fields=[
                ('cod_dir_transv', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_directorio', models.CharField(max_length=255)),
                ('ruta_completa', models.CharField(max_length=600)),
                ('ruta_relativa', models.CharField(blank=True, max_length=500, null=True)),
                ('nivel_jerarquia', models.IntegerField(default=0, null=True)),
                ('total_archivos', models.IntegerField(default=0, null=True)),
                ('total_subdirectorios', models.IntegerField(default=0, null=True)),
                ('peso_total_bytes', models.BigIntegerField(default=0, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_ultimo_escaneo', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('cod_municipio', models.ForeignKey(db_column='cod_municipio', on_delete=django.db.models.deletion.CASCADE, to='preoperacion.municipios')),
                ('directorio_padre', models.ForeignKey(blank=True, db_column='directorio_padre', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.directoriostransv')),
            ],
            options={
                'verbose_name': 'Directorio Transversal',
                'verbose_name_plural': 'Directorios Transversales',
                'db_table': 'directorios_transv',
                'ordering': ['cod_municipio', 'nivel_jerarquia', 'nombre_directorio'],
            },
        ),
        migrations.CreateModel(
            name='ArchivosTransv',
            fields=[
                ('id_archivo_transv', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('path_file', models.CharField(max_length=600)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_disposicion', models.DateTimeField(blank=True, null=True)),
                ('usuario_windows', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_memoria', models.BigIntegerField(default=0, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('es_directorio_especial', models.BooleanField(default=False, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_ultimo_escaneo', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('activo', models.BooleanField(default=True, null=True)),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('cod_dir_transv', models.ForeignKey(db_column='cod_dir_transv', help_text='Referencia al directorio transversal', on_delete=django.db.models.deletion.CASCADE, to='app.directoriostransv')),
            ],
            options={
                'verbose_name': 'Archivo Transversal',
                'verbose_name_plural': 'Archivos Transversales',
                'db_table': 'archivos_transv',
                'ordering': ['-fecha_creacion', 'nombre_archivo'],
            },
        ),
        migrations.CreateModel(
            name='PathDirOpera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(help_text='Ruta completa del directorio de operación')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro')),
                ('cod_municipio', models.ForeignKey(db_column='cod_municipio', help_text='Código del municipio (FK a municipios)', on_delete=django.db.models.deletion.CASCADE, to='preoperacion.municipios')),
            ],
            options={
                'verbose_name': 'Ruta de Directorio Operativo',
                'verbose_name_plural': 'Rutas de Directorios Operativos',
                'db_table': 'path_dir_opera',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PathDirTransv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(help_text='Ruta completa del directorio de transversal')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro')),
                ('cod_municipio', models.ForeignKey(db_column='cod_municipio', help_text='Código del municipio (FK a municipios)', on_delete=django.db.models.deletion.CASCADE, to='preoperacion.municipios')),
            ],
            options={
                'verbose_name': 'Ruta de Directorio Transversal',
                'verbose_name_plural': 'Rutas de Directorios Transversal',
                'db_table': 'path_dir_transv',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ScriptExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('script_name', models.CharField(choices=[('backup_db', 'Copia de Seguridad de Base de Datos'), ('llenar_datos', 'Llenar Datos de Directorios')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output_file', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('output_log', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejecución de Script',
                'verbose_name_plural': 'Ejecuciones de Scripts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_files', to='app.scriptexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
